# Generated by Django 4.1.7 on 2023-03-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_people',
            new_name='people',
        ),
    ]
