# Generated by Django 4.1.7 on 2023-03-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_phone_number_reservation_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='people',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number',
            new_name='phone_number',
        ),
    ]
